# Generated by Django 5.2.5 on 2025-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_role',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('inventory', 'Inventory Manager'), ('sales', 'Salesperson'), ('support', 'Support Staff')], max_length=20, null=True),
        ),
    ]
